#config.yaml

genome: resources/GRCh38_full_analysis_set_plus_decoy_hla.fa

intervals: resources/SureSelectV8.wes.mod.bed

Strelka2_intervals: resources/SureSelectV8.wes.mod.strelka2.bed.gz

chr_to_exclude: resources/GRCh38_full_analysis_set_plus_decoy_hla.exclude.txt

gnomAD: resources/af-only-gnomad.hg38.norm.vcf.gz

gatk_pon: resources/1000g_pon.hg38.norm.vcf.gz

dbNSFP: resources/dbNSFP4.5a_grch38.gz

clinvar: resources/clinvar_20231217.vcf.gz

vepcache: resources/vep/cache/
  
run_mode: nocontrol # must be one of the following: nocontrol, PoN , paired

Strelka2: resources/strelka-2.9.10.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py

samples:

  sample1: HG00145
#  sample2: HG00239
#  sample3: NA20505

strand:
  
  strandR1: R1
  strandR2: R2

# Set number of cores 
threads: 20

# PARAMETERS FOR CONTROLS FILTERING 
filtering_controls:

## Minimum read depth to call a variant (100 suggested)   
  min_depth: 1

## Minimum variant allele frequency (5% suggested)  
  vaf: 0

## Minimum variant supporting reads (5 suggested)   
  alt_depth: 1

# PARAMETERS FOR SAMPLES FILTERING 
filtering_tumors:
  
  ## Minimum read depth to call a variant (100 suggested)   
  min_depth: 20

  ## Minimum variant allele frequency (5% suggested)  
  vaf: 0.03

  ## Minimum variant supporting reads (5 suggested)   
  alt_depth: 2


callers:
  
  caller1: mutect2
  caller2: freebayes
  caller3: bcftools
  caller4: varscan
  caller5: strelka2
